"use client";

import { Archive, BriefcaseBusiness, Clock3, Download, Plus, Search, Users, X } from "lucide-react";
import { useMemo, useState } from "react";
import { OpportunityCard } from "@/components/admin/opportunities/opportunity-card";
import { OpportunityDialog } from "@/components/admin/opportunities/opportunity-dialog";
import { OpportunityTable } from "@/components/admin/opportunities/opportunity-table";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { opportunities, opportunityKpis, type Opportunity } from "@/lib/mock-data/opportunities";
import { downloadCsv, readAdminStorage, writeAdminStorage } from "@/lib/admin-storage";
import { ConfirmationDialog } from "@/components/admin/shared/confirmation-dialog";
import { ReasonDialog } from "@/components/admin/shared/reason-dialog";
import { NoResultsState } from "@/components/admin/admin-state";

const iconMap = { briefcase: BriefcaseBusiness, clock: Clock3, archive: Archive, users: Users };
const statuses = ["All statuses", "Pending Approval", "Live", "Expired", "Rejected", "Draft"];

export default function AdminOpportunitiesPage() {
  const [items, setItems] = useState(() => readAdminStorage<Opportunity[]>("skillconnect-admin-opportunities", opportunities));
  const [search, setSearch] = useState("");
  const [company, setCompany] = useState("All companies");
  const [type, setType] = useState("All types");
  const [status, setStatus] = useState("All statuses");
  const [department, setDepartment] = useState("All departments");
  const [page, setPage] = useState(1);
  const [selected, setSelected] = useState<Opportunity>();
  const [dialogOpen, setDialogOpen] = useState(false);
  const [dialogMode, setDialogMode] = useState<"details" | "form">("details");
  const [confirmTarget, setConfirmTarget] = useState<{ item: Opportunity; action: string } | null>(null);
  const [rejectTarget, setRejectTarget] = useState<Opportunity | null>(null);
  const filtered = useMemo(() => items.filter((item) => `${item.title} ${item.company.name} ${item.skills.join(" ")}`.toLowerCase().includes(search.toLowerCase()) && (company === "All companies" || item.company.name === company) && (type === "All types" || item.type === type) && (status === "All statuses" || item.status === status) && (department === "All departments" || item.department === department)), [items, search, company, type, status, department]);
  const pageCount = Math.max(1, Math.ceil(filtered.length / 10));
  const visible = filtered.slice((page - 1) * 10, page * 10);
  const performMutation = (item: Opportunity, action: string, reason?: string) => { const nextStatus = action === "Approve" ? "Live" : action === "Reject" ? "Rejected" : action === "Disable" ? "Expired" : item.status; const nextItems = items.map((entry) => entry.id === item.id ? { ...entry, status: nextStatus, approvalHistory: reason ? [...entry.approvalHistory, `Rejected by admin: ${reason}`] : entry.approvalHistory } : entry); setItems(nextItems); writeAdminStorage("skillconnect-admin-opportunities", nextItems); setDialogOpen(false); };
  const mutate = (item: Opportunity, action: string) => { if (action === "Reject") setRejectTarget(item); else if (["Approve", "Disable"].includes(action)) setConfirmTarget({ item, action }); else performMutation(item, action); };
  const reset = () => { setSearch(""); setCompany("All companies"); setType("All types"); setStatus("All statuses"); setDepartment("All departments"); setPage(1); };
  const pending = items.filter((item) => item.status === "Pending Approval");
  const saveOpportunity = (item: Opportunity) => { const nextItems = items.some((entry) => entry.id === item.id) ? items.map((entry) => entry.id === item.id ? item : entry) : [item, ...items]; setItems(nextItems); writeAdminStorage("skillconnect-admin-opportunities", nextItems); };
  const exportCsv = () => downloadCsv("skillconnect-opportunities.csv", filtered.map((item) => ({ title: item.title, company: item.company.name, type: item.type, status: item.status, applications: item.applications, deadline: item.deadline })));
  return <div className="mx-auto max-w-7xl space-y-8 pb-10"><Header onAdd={() => { setSelected(undefined); setDialogMode("form"); setDialogOpen(true); }} onExport={exportCsv} /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{opportunityKpis.map((item) => { const Icon = iconMap[item.icon as keyof typeof iconMap]; return <Card key={item.title} className="p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.12em] text-muted">{item.title}</p><p className="mt-3 text-3xl font-semibold tracking-tight text-ink">{item.value}</p><p className="mt-2 text-xs font-medium text-emerald-600">{item.trend}</p></div><div className={`rounded-xl p-3 text-white ${item.accent}`}><Icon className="h-5 w-5" /></div></div></Card>; })}</div>
    <Card><CardHeader className="border-b border-line"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-center"><div><CardTitle>Opportunity catalogue</CardTitle><p className="mt-1 text-sm text-muted">Review {filtered.length} opportunities across all industry partners.</p></div><div className="relative w-full lg:w-80"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted" /><Input value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }} placeholder="Search job title, company, skill..." className="pl-9" /></div></div><div className="flex flex-wrap gap-2 pt-4"><Filter value={company} onChange={setCompany} options={["All companies", ...new Set(items.map((item) => item.company.name))]} /><Filter value={type} onChange={setType} options={["All types", "Internship", "Full-Time", "Apprenticeship"]} /><Filter value={status} onChange={setStatus} options={statuses} /><Filter value={department} onChange={setDepartment} options={["All departments", ...new Set(items.map((item) => item.department))]} /><Button variant="ghost" size="sm" onClick={reset}><X className="h-3.5 w-3.5" />Reset Filters</Button></div></CardHeader><CardContent className="p-0">{filtered.length ? <><OpportunityTable opportunities={visible} onView={(item) => { setSelected(item); setDialogMode("details"); setDialogOpen(true); }} onEdit={(item) => { setSelected(item); setDialogMode("form"); setDialogOpen(true); }} onAction={mutate} /><Pagination page={page} pageCount={pageCount} total={filtered.length} onPage={setPage} /></> : <NoResultsState onReset={reset} />}</CardContent></Card>
    <section><SectionTitle title="Pending approval queue" eyebrow="Admin review" /><div className="grid gap-4 lg:grid-cols-2">{pending.map((item) => <OpportunityCard key={item.id} opportunity={item} onView={(entry) => { setSelected(entry); setDialogOpen(true); }} onApprove={(entry) => mutate(entry, "Approve")} onReject={(entry) => mutate(entry, "Reject")} />)}</div></section>
    <section><SectionTitle title="Opportunity analytics preview" eyebrow="Performance snapshot" /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Most applied opportunity", "Software Development Engineer", "622 applications"], ["Highest stipend opportunity", "AI Product Intern", "₹60,000/mo"], ["Least applied opportunity", "Embedded Systems Engineer", "74 applications"], ["Expiring this week", "Cloud Engineering Intern", "Sep 14, 2026"]].map(([title, value, detail]) => <Card key={title} className="p-5"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-muted">{title}</p><p className="mt-4 font-semibold text-ink">{value}</p><p className="mt-1 text-xs text-muted">{detail}</p></Card>)}</div></section>
    <OpportunityDialog mode={dialogMode} opportunity={selected} open={dialogOpen} onOpenChange={setDialogOpen} onSave={saveOpportunity} onAction={(action) => selected && (action === "Edit" ? setDialogMode("form") : mutate(selected, action))} /><ConfirmationDialog open={Boolean(confirmTarget)} onOpenChange={(open) => !open && setConfirmTarget(null)} title={`${confirmTarget?.action ?? "Confirm"} opportunity?`} description="This status change will be saved in this browser for the admin workspace." onConfirm={() => { if (confirmTarget) performMutation(confirmTarget.item, confirmTarget.action); setConfirmTarget(null); }} /><ReasonDialog open={Boolean(rejectTarget)} onOpenChange={(open) => !open && setRejectTarget(null)} title="Reject opportunity" description="A rejection reason is required for the industry partner." confirmLabel="Reject opportunity" onConfirm={(reason) => { if (rejectTarget) performMutation(rejectTarget, "Reject", reason); setRejectTarget(null); }} /></div>;
}
  function Header({ onAdd, onExport }: { onAdd: () => void; onExport: () => void }) { return <div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-[0.68rem] font-semibold uppercase tracking-[0.18em] text-indigo-600">Administration / Industry</p><h1 className="mt-2 font-display text-4xl font-semibold tracking-[-0.06em] text-ink">Opportunities Management</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted">Review, approve and monitor internships and placement opportunities posted by industries.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={onExport}><Download className="h-4 w-4" />Export Opportunities</Button><Button onClick={onAdd}><Plus className="h-4 w-4" />Add Opportunity</Button></div></div>; }
function Filter({ value, onChange, options }: { value: string; onChange: (value: string) => void; options: string[] }) { return <select value={value} onChange={(e) => onChange(e.target.value)} className="h-9 rounded-xl border border-line bg-white px-3 text-xs font-medium text-ink outline-none focus:ring-2 focus:ring-indigo-300">{options.map((option) => <option key={option}>{option}</option>)}</select>; }
function SectionTitle({ eyebrow, title }: { eyebrow: string; title: string }) { return <div className="mb-4"><p className="text-[0.68rem] font-semibold uppercase tracking-[0.16em] text-indigo-600">{eyebrow}</p><h2 className="mt-1 text-2xl font-semibold tracking-tight text-ink">{title}</h2></div>; }
function Pagination({ page, pageCount, total, onPage }: { page: number; pageCount: number; total: number; onPage: (page: number) => void }) { return <div className="flex items-center justify-between border-t border-line px-5 py-4"><p className="text-xs text-muted">Showing {total ? (page - 1) * 10 + 1 : 0}-{Math.min(page * 10, total)} of {total}</p><div className="flex gap-2"><Button size="sm" variant="outline" disabled={page === 1} onClick={() => onPage(page - 1)}>Previous</Button><Button size="sm" variant="outline" disabled={page === pageCount} onClick={() => onPage(page + 1)}>Next</Button></div></div>; }
