"use client";

import { Award, ClipboardCheck, Database, Download, FileText, Library, Plus, Search, Users, X } from "lucide-react";
import { useSearchParams } from "next/navigation";
import { Suspense, useMemo, useState } from "react";
import { AssessmentCard } from "@/components/admin/assessments/assessment-card";
import { AssessmentDialog } from "@/components/admin/assessments/assessment-dialog";
import { AssessmentStatusBadge } from "@/components/admin/assessments/assessment-status-badge";
import { AssessmentTable } from "@/components/admin/assessments/assessment-table";
import { CompletionProgress } from "@/components/admin/assessments/completion-progress";
import { CreateAssessmentDialog } from "@/components/admin/assessments/create-assessment-dialog";
import { PerformanceCard } from "@/components/admin/assessments/performance-card";
import { QuestionManagerDialog } from "@/components/admin/assessments/question-manager-dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { assessmentKpis, assessments as initialAssessments, categories, departmentPerformance, lowCompletionAlerts, participation, questions, upcomingAssessments, type Assessment } from "@/lib/mock-data/assessments";
import { useMockStore } from "@/lib/mock-store";
import { readAdminStorage, writeAdminStorage } from "@/lib/admin-storage";
import { ConfirmationDialog } from "@/components/admin/shared/confirmation-dialog";
import { NoResultsState } from "@/components/admin/admin-state";
import { savePublishedAssessment } from "@/lib/assessment-storage";

const icons = { library: Library, activity: ClipboardCheck, file: FileText, database: Database, users: Users, award: Award };

function AdminAssessmentsPageInner() {
  const searchParams = useSearchParams();
  const [items, setItems] = useState(() => readAdminStorage("skillconnect-admin-assessments", initialAssessments));
  const { publishAssessment } = useMockStore();
  const [search, setSearch] = useState("");
  const [category, setCategory] = useState("All categories");
  const [skill, setSkill] = useState("All skills");
  const [difficulty, setDifficulty] = useState("All difficulties");
  const [status, setStatus] = useState("All statuses");
  const [page, setPage] = useState(1);
  const [selected, setSelected] = useState<Assessment>();
  const [detailsOpen, setDetailsOpen] = useState(false);
  const [createOpen, setCreateOpen] = useState(() => searchParams.get("create") === "true");
  const [question, setQuestion] = useState<(typeof questions)[number]>();
  const [questionOpen, setQuestionOpen] = useState(false);

  const filtered = useMemo(() => items.filter((item) => `${item.title} ${item.skill}`.toLowerCase().includes(search.toLowerCase()) && (category === "All categories" || item.category === category) && (skill === "All skills" || item.skill === skill) && (difficulty === "All difficulties" || item.difficulty === difficulty) && (status === "All statuses" || item.status === status)), [items, search, category, skill, difficulty, status]);
  const pageCount = Math.max(1, Math.ceil(filtered.length / 10));
  const visible = filtered.slice((page - 1) * 10, page * 10);
  const save = (item: Assessment) => { const nextItems = items.some((entry) => entry.id === item.id) ? items.map((entry) => entry.id === item.id ? item : entry) : [item, ...items]; setItems(nextItems); writeAdminStorage("skillconnect-admin-assessments", nextItems); if (item.status === "Active") { const itemQuestions = questions.filter((question) => question.skill === item.skill).slice(0, 5); savePublishedAssessment({ ...item, questions: itemQuestions.length ? itemQuestions : questions.slice(0, 5) }); publishAssessment({ id: item.id, title: item.title, skill: item.skill, department: item.assignedDepartments[0] ?? "Computer Engineering", semester: "Semester 6", deadline: "2026-09-30", status: "Published", assignment: { departments: item.assignedDepartments, semesters: ["Semester 6"], studentIds: ["student-1"] }, questions: itemQuestions.length ? itemQuestions : questions.slice(0, 5) }); } };
  const [confirmTarget, setConfirmTarget] = useState<{ item: Assessment; action: string } | null>(null);
  const action = (item: Assessment, selectedAction: string) => { if (["Delete", "Archive"].includes(selectedAction)) setConfirmTarget({ item, action: selectedAction }); if (selectedAction === "Duplicate") save({ ...item, id: `assessment-${Date.now()}`, title: `${item.title} (Copy)`, status: "Draft" }); };
  const performAction = (item: Assessment, selectedAction: string) => { const nextItems = selectedAction === "Delete" ? items.filter((entry) => entry.id !== item.id) : items.map((entry) => entry.id === item.id ? { ...entry, status: "Archived" as const } : entry); setItems(nextItems); writeAdminStorage("skillconnect-admin-assessments", nextItems); };
  const reset = () => { setSearch(""); setCategory("All categories"); setSkill("All skills"); setDifficulty("All difficulties"); setStatus("All statuses"); setPage(1); };
  return <div className="mx-auto max-w-7xl space-y-8 pb-10"><Header onCreate={() => { setSelected(undefined); setCreateOpen(true); }} /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{assessmentKpis.map((item) => { const Icon = icons[item.icon as keyof typeof icons]; return <Card key={item.title} className="p-5 transition hover:-translate-y-1 hover:shadow-md"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.1em] text-muted">{item.title}</p><p className="mt-3 text-3xl font-semibold tracking-tight text-ink">{item.value}</p><p className="mt-2 text-xs font-semibold text-emerald-600">{item.trend}</p></div><div className={`rounded-xl p-3 text-white ${item.accent}`}><Icon className="h-5 w-5" /></div></div></Card>; })}</div>
    <Card><div className="border-b border-line p-5"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-center"><div><h2 className="text-xl font-semibold tracking-tight text-ink">Assessment library</h2><p className="mt-1 text-sm text-muted">{filtered.length} assessments matching your filters</p></div><div className="relative w-full lg:w-80"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted" /><Input value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }} placeholder="Search assessments..." className="pl-9" /></div></div><div className="flex flex-wrap gap-2 pt-4"><Filter value={category} onChange={setCategory} options={["All categories", "Technical", "Soft Skills", "Domain", "Emerging"]} /><Filter value={skill} onChange={setSkill} options={["All skills", ...new Set(items.map((item) => item.skill))]} /><Filter value={difficulty} onChange={setDifficulty} options={["All difficulties", "Beginner", "Intermediate", "Advanced"]} /><Filter value={status} onChange={setStatus} options={["All statuses", "Active", "Draft", "Scheduled", "Completed", "Archived"]} /><Filter value="Any completion" onChange={() => undefined} options={["Any completion", "Below 60%", "60% or higher"]} /><Filter value="Any created date" onChange={() => undefined} options={["Any created date", "This month", "This quarter"]} /><Button variant="ghost" size="sm" onClick={reset}><X className="h-3.5 w-3.5" />Reset Filters</Button></div></div><div className="p-0">{filtered.length ? <><AssessmentTable assessments={visible} onView={(item) => { setSelected(item); setDetailsOpen(true); }} onEdit={(item) => { setSelected(item); setCreateOpen(true); }} onAction={action} /><Pagination page={page} pageCount={pageCount} total={filtered.length} onPage={setPage} /></> : <NoResultsState onReset={reset} />}</div></Card>
    <section><div className="flex flex-col sm:flex-row sm:items-center sm:justify-between mb-2"><Title eyebrow="Question bank" title="Question Bank Manager" /><Button size="sm" onClick={() => { setSelected(undefined); setCreateOpen(true); }} className="mb-4 sm:mb-0 gap-1.5"><Plus className="h-4 w-4" />Create Assessment with Q/A</Button></div><div className="mb-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[["Total Questions", questions.length], ["Technical Questions", questions.filter((item) => ["Python", "Java", "React", "SQL", "Git", "Docker"].includes(item.skill)).length], ["Soft Skill Questions", questions.filter((item) => ["Communication", "Leadership", "Teamwork"].includes(item.skill)).length], ["MCQs", questions.filter((item) => item.type === "MCQ").length], ["Coding Questions", questions.filter((item) => item.type === "Coding").length]].map(([label, value]) => <Card key={label} className="p-4"><p className="text-xs text-muted">{label}</p><p className="mt-2 text-2xl font-semibold text-ink">{value}</p></Card>)}</div><Card className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="border-b border-line bg-slate-50"><tr>{["Question", "Skill", "Type", "Difficulty", "Status", "Actions"].map((head) => <th key={head} className="px-5 py-3 text-left text-[0.68rem] font-semibold uppercase tracking-[0.12em] text-muted">{head}</th>)}</tr></thead><tbody>{questions.slice(0, 10).map((item) => <tr key={item.id} className="border-b border-line last:border-0"><td className="max-w-md px-5 py-4 font-medium text-ink">{item.text}</td><td className="px-5 py-4 text-xs text-muted">{item.skill}</td><td className="px-5 py-4"><Badge variant="info">{item.type}</Badge></td><td className="px-5 py-4"><AssessmentStatusBadge status={item.difficulty} /></td><td className="px-5 py-4"><Badge variant={item.status === "Active" ? "success" : "danger"}>{item.status}</Badge></td><td className="px-5 py-4"><Button size="sm" variant="ghost" onClick={() => { setQuestion(item); setQuestionOpen(true); }}>Preview</Button></td></tr>)}</tbody></table></div></Card></section>
    <section><Title eyebrow="Participation" title="Assessment Participation" /><Card className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="border-b border-line bg-slate-50"><tr>{["Assessment", "Participants", "Completed", "Ongoing", "Not started", "Average score", "Highest", "Lowest", "Department"].map((head) => <th key={head} className="px-4 py-3 text-left text-[0.65rem] font-semibold uppercase tracking-[0.1em] text-muted">{head}</th>)}</tr></thead><tbody>{participation.map((item) => <tr key={item.assessment} className="border-b border-line last:border-0"><td className="px-4 py-4 font-semibold text-ink">{item.assessment}</td><td className="px-4 py-4">{item.participants}</td><td className="px-4 py-4"><CompletionProgress value={Math.round(item.completed / item.participants * 100)} /></td><td className="px-4 py-4">{item.ongoing}</td><td className="px-4 py-4">{item.notStarted}</td><td className="px-4 py-4">{item.averageScore}%</td><td className="px-4 py-4 text-emerald-600">{item.highestScore}%</td><td className="px-4 py-4 text-orange-600">{item.lowestScore}%</td><td className="px-4 py-4 text-xs text-muted">{item.department}</td></tr>)}</tbody></table></div></Card></section>
    <section><Title eyebrow="Department outcomes" title="Department Performance" /><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{departmentPerformance.map((item) => <PerformanceCard key={item.department} {...item} />)}</div></section>
    <section><Title eyebrow="Attention required" title="Low Completion Alerts" /><div className="grid gap-4 md:grid-cols-2">{lowCompletionAlerts.map((item) => <Card key={item.name} className="flex items-center justify-between gap-4 border-orange-200 p-5"><div><p className="font-semibold text-ink">{item.name}</p><p className="mt-1 text-xs text-muted">{item.department} · {item.pendingStudents} students pending</p><div className="mt-3 flex items-center gap-2"><CompletionProgress value={item.completion} /><span className="text-xs font-semibold text-orange-600">{item.completion}% complete</span></div></div><Button size="sm" variant="outline">Send Reminder</Button></Card>)}</div></section>
    <section><Title eyebrow="Leaderboard" title="Top Performing Assessments" /><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-5">{items.slice().sort((a, b) => b.averageScore - a.averageScore).slice(0, 5).map((item, index) => <Card key={item.id} className="p-4"><div className="flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-indigo-50 font-bold text-indigo-700">{index + 1}</span><p className="font-semibold text-ink">{item.title}</p></div><p className="mt-4 text-2xl font-semibold text-indigo-700">{item.averageScore}%</p><p className="mt-1 text-xs text-muted">{item.participants} participants · {item.completionRate}% completion</p><div className="mt-3"><AssessmentStatusBadge status={item.difficulty} /></div></Card>)}</div></section>
    <section><Title eyebrow="Scheduled learning" title="Upcoming Assessments" /><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{upcomingAssessments.map((item) => <AssessmentCard key={item.name} assessment={item} onView={() => { const match = items.find((entry) => entry.title.includes(item.name)); if (match) { setSelected(match); setDetailsOpen(true); } }} />)}</div></section>
    <section><Title eyebrow="Catalogue mix" title="Assessment Categories" /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{categories.map((item) => <Card key={item.name} className="p-5"><p className="font-semibold text-ink">{item.name}</p><p className="mt-1 text-xs text-muted">{item.assessments} assessments · {item.questions} questions</p><div className="mt-4"><CompletionProgress value={item.completion} /></div><p className="mt-3 text-xs text-muted">Average score <strong className="text-ink">{item.averageScore}%</strong></p></Card>)}</div></section>
    {selected && <AssessmentDialog assessment={selected} open={detailsOpen} onOpenChange={setDetailsOpen} onAction={(selectedAction) => selectedAction === "Edit" ? setCreateOpen(true) : action(selected, selectedAction)} />}<CreateAssessmentDialog key={selected?.id ?? "new"} assessment={selected} open={createOpen} onOpenChange={setCreateOpen} onSave={save} /><QuestionManagerDialog question={question} open={questionOpen} onOpenChange={setQuestionOpen} /><ConfirmationDialog open={Boolean(confirmTarget)} onOpenChange={(open) => !open && setConfirmTarget(null)} title={`${confirmTarget?.action ?? "Confirm"} assessment?`} description="This change will be saved in this browser for the admin workspace." onConfirm={() => { if (confirmTarget) performAction(confirmTarget.item, confirmTarget.action); setConfirmTarget(null); }} />
  </div>;
}
function Header({ onCreate }: { onCreate: () => void }) { return <div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-[0.68rem] font-semibold uppercase tracking-[0.18em] text-indigo-600">Administration / Evaluation</p><h1 className="mt-2 font-display text-4xl font-semibold tracking-[-0.06em] text-ink">Assessment Management</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted">Create, manage and monitor skill assessments across the SkillConnect platform.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline"><Download className="h-4 w-4" />Export Assessments</Button><Button onClick={onCreate}><Plus className="h-4 w-4" />Create Assessment</Button></div></div>; }
function Filter({ value, onChange, options }: { value: string; onChange: (value: string) => void; options: string[] }) { return <select value={value} onChange={(e) => onChange(e.target.value)} className="h-9 rounded-xl border border-line bg-white px-3 text-xs font-medium text-ink outline-none focus:ring-2 focus:ring-indigo-300">{options.map((option) => <option key={option}>{option}</option>)}</select>; }
function Title({ eyebrow, title }: { eyebrow: string; title: string }) { return <div className="mb-4"><p className="text-[0.68rem] font-semibold uppercase tracking-[0.16em] text-indigo-600">{eyebrow}</p><h2 className="mt-1 text-2xl font-semibold tracking-tight text-ink">{title}</h2></div>; }
function Pagination({ page, pageCount, total, onPage }: { page: number; pageCount: number; total: number; onPage: (page: number) => void }) { return <div className="flex items-center justify-between border-t border-line px-5 py-4"><p className="text-xs text-muted">Showing {total ? (page - 1) * 10 + 1 : 0}-{Math.min(page * 10, total)} of {total}</p><div className="flex gap-2"><Button size="sm" variant="outline" disabled={page === 1} onClick={() => onPage(page - 1)}>Previous</Button><Button size="sm" variant="outline" disabled={page === pageCount} onClick={() => onPage(page + 1)}>Next</Button></div></div>; }

export default function AdminAssessmentsPage() {
  return (
    <Suspense fallback={<div className="p-8 text-center text-sm text-muted">Loading assessments...</div>}>
      <AdminAssessmentsPageInner />
    </Suspense>
  );
}
